abstraction:
  precision: 8
  type: mask
  total_abstraction: 200
  percentage_of_actions_ignored_at_the_extremes: 0.0
planner:
  replan: true
  try_random: false
  type: mega
  action_size: 1200
simulation:
  experience_data: /home/davide/Documenti/gitProject/REAL2020_starter_kit/2749.npy
  extrinsic_steps: 10000
  save_images: true
  save_masks: true
  use_experience_data: true
