abstraction:
  precision: 8
  type: pos_noq
  total_abstraction: 200
  percentage_of_actions_ignored_at_the_extremes: 0.05
planner:
  replan: true
  try_random: false
  type: mega
  action_size: 1200
simulation:
  experience_data: baseline/transitions_DiscreteActionsCollector_12500000_1_472222_xy_push.npy
  extrinsic_steps: 10000
  save_images: false
  save_masks: false
  use_experience_data: false
