abstraction:
  precision: 8
  type: pos_noq
  total_abstraction: 200
  percentage_of_actions_ignored_at_the_extremes: 0.05
planner:
  replan: true
  try_random: false
  type: mega
simulation:
  experience_data: baseline/filtered_transitions_15000000_12486_1_4170_466197_60x128_pos_noq_4_xy_push.npy
  extrinsic_steps: 10000
  save_images: false
  save_masks: false
  use_experience_data: true
